(()=>{const S=JSON.parse(localStorage.glowSession||"null"),role=document.body.dataset.role;
if(!S||S.role!==role){location.replace("login.html");return}
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],ini=n=>n.split(" ").map(w=>w[0]).slice(0,2).join("").toUpperCase();
const toast=t=>{const e=$("#toast");e.textContent=t;e.classList.add("on");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("on"),2400)};
const adm=role==="admin";
/* ---- data ---- */
let mails=adm?[
{id:1,from:"Meera Sharma",sub:"Reschedule my pigmentation session",body:"Hi team, could I move Friday's session to Saturday morning? I have a travel plan that came up. Thank you!",time:"09:12",un:1,box:"in"},
{id:2,from:"Priya Kapoor",sub:"Thank you for the acne care plan",body:"Just wanted to say my skin is clearer after three weeks. The routine is simple and I actually follow it.",time:"Yesterday",un:1,box:"in"},
{id:3,from:"Stackly Supplies",sub:"Invoice #4021 — hydration serums",body:"Your monthly stock of hydration serums has shipped. Delivery is expected within three working days.",time:"Yesterday",un:0,box:"in"},
{id:4,from:"Divya Menon",sub:"Question about winter hydration therapy",body:"Is it safe to combine the hydration therapy with a mild peel in the same month?",time:"Mon",un:1,box:"in"},
{id:5,from:"Dr. Rao (Dermatology)",sub:"Weekly case review",body:"Sharing notes for this week's case review. Please confirm availability for Thursday afternoon.",time:"Sun",un:0,box:"in"}]:[
{id:1,from:"Stackly Care Team",sub:"Your Hydra Facial is confirmed",body:"Your Signature HydraFacial is booked for Friday at 11:30 AM. Please arrive 10 minutes early with a clean face.",time:"08:40",un:1,box:"in"},
{id:2,from:"Care Team",sub:"Your personalised routine is ready",body:"We have updated your morning and night routine based on last week's skin analysis. Open 'My Routine' to see it.",time:"Yesterday",un:1,box:"in"},
{id:3,from:"Stackly Rewards",sub:"You earned 120 glow points",body:"Thank you for staying consistent! 120 points were added to your wallet and can be used on your next visit.",time:"Mon",un:0,box:"in"}];
const clients=[["Meera Sharma","Pigmentation","VIP"],["Priya Kapoor","Acne Care","Active"],["Divya Menon","Hydration","Active"],["Ananya Rao","Advanced Facial","VIP"],["Kavya Nair","Anti-ageing","New"],["Isha Verma","Glow Peel","Active"],["Riya Shah","Laser Care","New"],["Sana Khan","Hydration","Active"]];
const appts=[["09:30","Meera Sharma","Pigmentation Care","ok"],["11:00","Priya Kapoor","Acne Therapy","ok"],["12:30","Divya Menon","Hydration Therapy","wait"],["15:00","Ananya Rao","HydraFacial","ok"],["16:30","Kavya Nair","Anti-ageing Peel","wait"]];
const mailBox=()=>`<div class="mail" id="mail"><div><div class="tools"><input id="ms" placeholder="Search messages…" aria-label="Search messages"><button class="btn btn--p" id="cmp">+ Compose</button></div><div class="tabs" id="mt" style="margin-bottom:12px"><button data-b="in" class="on">Inbox</button><button data-b="un">Unread</button><button data-b="out">Sent</button></div><div class="mail__l" id="ml"></div></div><div class="mail__r" id="mr"></div></div>`;
/* ---- views ---- */
const V={};
const bars=(a)=>`<div class="bars">${a.map(([l,v],i)=>`<div><i style="height:${v}%;--i:${i}"></i>${l}</div>`).join("")}</div>`;
V.overview=()=>adm?`<div class="grid">
<div class="box stat dk c3 a"><span>Today's revenue</span><b data-n="48200" data-p="₹">0</b><em>▲ 12% vs yesterday</em></div>
<div class="box stat c3 a" style="--i:1"><span>Appointments</span><b data-n="24">0</b><em>5 pending</em></div>
<div class="box stat c3 a" style="--i:2"><span>Active clients</span><b data-n="1286">0</b><em>▲ 38 this week</em></div>
<div class="box stat c3 a" style="--i:3"><span>Unread mails</span><b data-n="${mails.filter(m=>m.un).length}">0</b><em>Check inbox</em></div>
<div class="box c8 a" style="--i:4"><h3>Weekly revenue</h3>${bars([["Mon",45],["Tue",62],["Wed",50],["Thu",78],["Fri",92],["Sat",100],["Sun",58]])}</div>
<div class="box c4 a" style="--i:5"><h3>Treatment mix</h3><div class="donut" style="background:conic-gradient(var(--g) 0 38%,var(--p) 38% 66%,#8fbfa8 66% 86%,#d9c6b8 86%)"><b>4</b></div><div class="lg"><span><i style="background:var(--g)"></i>Facials</span><span><i style="background:var(--p)"></i>Peels</span><span><i style="background:#8fbfa8"></i>Hydration</span><span><i style="background:#d9c6b8"></i>Laser</span></div></div>
<div class="box c12 a" style="--i:6"><h3>Today's schedule</h3><div class="tl">${appts.map(a=>`<div><b>${a[0]}</b> · ${a[1]}<br><span style="color:var(--mu);font-size:.85rem">${a[2]}</span> <span class="chip ${a[3]}">${a[3]==="ok"?"Confirmed":"Pending"}</span></div>`).join("")}</div></div></div>`:
`<div class="grid"><div class="box c4 a"><h3>Glow score</h3><div class="ring" style="background:conic-gradient(var(--p),var(--g2) 82%,var(--m) 0)"><b>82</b></div><p style="text-align:center;color:var(--mu);margin-top:12px">+6 points this month ✦</p></div>
<div class="box c8 a" style="--i:1"><h3>Next appointment</h3><div class="row" style="padding:18px"><div class="av" style="width:58px;height:58px">Fri</div><div class="t"><b>Signature HydraFacial</b><span>11:30 AM · Stackly Care Team · Room 2</span></div><span class="chip ok">Confirmed</span></div>
<h3 style="margin-top:20px">Skin vitals</h3><p>Hydration</p><div class="bar"><i style="width:78%"></i></div><p style="margin-top:8px">Radiance</p><div class="bar"><i style="width:64%"></i></div><p style="margin-top:8px">Barrier health</p><div class="bar"><i style="width:88%"></i></div></div>
<div class="box stat c4 a" style="--i:2"><span>Glow points</span><b data-n="460">0</b><em>▲ 120 new</em></div><div class="box stat dk c4 a" style="--i:3"><span>Visits this year</span><b data-n="9">0</b><em style="color:var(--p)">Keep glowing</em></div><div class="box stat c4 a" style="--i:4"><span>Unread messages</span><b data-n="${mails.filter(m=>m.un).length}">0</b><em>Open inbox</em></div></div>`;
V.appointments=()=>`<div class="box a"><div class="tabs" id="ft" style="margin-bottom:16px"><button class="on" data-f="all">All</button><button data-f="ok">Confirmed</button><button data-f="wait">Pending</button></div><div class="list" id="al">${appts.map((a,i)=>`<div class="row" data-s="${a[3]}" style="animation:up .6s var(--e) backwards;animation-delay:${i*70}ms"><div class="av">${a[0].slice(0,2)}</div><div class="t"><b>${a[1]}</b><span>${a[0]} · ${a[2]}</span></div><span class="chip ${a[3]}">${a[3]==="ok"?"Confirmed":"Pending"}</span></div>`).join("")}</div></div>`;
V.clients=()=>`<div class="tools a"><input id="cs" placeholder="Search clients…" aria-label="Search clients"></div><div class="cards" id="cc">${clients.map((c,i)=>`<div class="box a" style="--i:${i}" data-k="${c[0].toLowerCase()}"><div class="av">${ini(c[0])}</div><b>${c[0]}</b><p style="color:var(--mu);font-size:.85rem">${c[1]}</p><span class="chip" style="margin-top:8px">${c[2]}</span></div>`).join("")}</div>`;
V.treatments=()=>`<div class="cards">${[["Signature HydraFacial",92],["Pigmentation Care",76],["Acne Therapy",84],["Glow Peel",68],["Anti-ageing Ritual",71],["Laser Rejuvenation",55]].map((t,i)=>`<div class="box a" style="--i:${i};text-align:left"><h3>${t[0]}</h3><p style="color:var(--mu);font-size:.85rem">Client satisfaction</p><div class="bar"><i style="width:${t[1]}%"></i></div><b style="font-family:'Lobster Two';font-size:1.4rem;color:var(--g)">${t[1]}%</b></div>`).join("")}</div>`;
V.bookings=()=>`<div class="box a"><h3>My visits</h3><div class="tl">${[["Fri, 11:30 AM","Signature HydraFacial","Upcoming"],["12 Sep","Glow Peel","Completed"],["28 Aug","Skin analysis","Completed"],["10 Aug","Acne Therapy","Completed"]].map(b=>`<div><b>${b[1]}</b><br><span style="color:var(--mu);font-size:.85rem">${b[0]}</span> <span class="chip ${b[2]==="Upcoming"?"wait":"ok"}">${b[2]}</span></div>`).join("")}</div></div>`;
const rt=[["Gentle cleanser",1],["Vitamin C serum",1],["Hydrating moisturiser",0],["SPF 50 sunscreen",0],["Night repair cream",0]];
V.routine=()=>`<div class="grid"><div class="box c6 a"><h3>Today's routine</h3>${rt.map((r,i)=>`<div class="chk ${r[1]?"on":""}" data-i="${i}"><i>✓</i><span>${r[0]}</span></div>`).join("")}</div><div class="box c6 a" style="--i:1"><h3>Progress</h3>${bars([["Mon",60],["Tue",75],["Wed",55],["Thu",90],["Fri",80],["Sat",100],["Sun",70]])}<p style="margin-top:14px;color:var(--mu)">Consistency builds glow — tap items to tick them off.</p></div></div>`;
V.profile=()=>`<div class="box a" style="max-width:560px"><h3>My profile</h3><div class="av" style="width:74px;height:74px;font-size:1.5rem;margin-bottom:16px">${ini(S.name)}</div><form id="pf" class="compose"><div class="fld"><input id="pn" value="${S.name}" placeholder=" "><label for="pn">Full name</label></div><div class="fld"><input value="${S.email}" placeholder=" " readonly><label>Email</label></div><div class="fld"><select><option>Combination</option><option>Dry</option><option>Oily</option><option>Sensitive</option></select><label>Skin type</label></div><button class="btn" type="submit">Save changes</button></form></div>`;
V.inbox=()=>mailBox();
/* ---- v2: images + richer content ---- */
const IM=(f,a="")=>`<img src="Assests/${f}.webp" alt="${a}" loading="lazy">`,av=i=>`avatar-${i%4+1}`,fn=S.name.split(" ")[0],hr=new Date().getHours(),gr=hr<12?"Good morning":hr<17?"Good afternoon":"Good evening",stars=n=>"★".repeat(n)+"☆".repeat(5-n);
const TR=[["Signature HydraFacial","detail-glow","₹3,500","60 min",92,"Deep cleanse, exfoliation and hydration in a single sitting."],["Pigmentation Care","detail-shadow","₹4,800","75 min",76,"Fades dark spots for an even, brighter tone."],["Acne Therapy","detail-face","₹2,900","50 min",84,"Calms breakouts and clears congested pores."],["Glow Peel","detail-lips","₹3,200","45 min",68,"A gentle peel that reveals fresh, smooth skin."],["Anti-ageing Ritual","detail-hands","₹5,400","90 min",71,"Firming massage with collagen-boosting serums."],["Laser Rejuvenation","detail-eyes","₹7,500","40 min",55,"Refines texture and softens fine lines."],["Hydrating Mask Therapy","detail-mask","₹2,400","40 min",88,"A cooling mask ritual for tired, dry skin."]];
const RV=[["Meera Sharma",5,"Pigmentation Care","My dark spots have faded a lot in six weeks, and the team explained every step."],["Priya Kapoor",5,"Acne Therapy","Clearer skin and a routine I can actually keep up with."],["Divya Menon",4,"Hydration Therapy","Skin felt plump for days. I would love an evening slot too."],["Kavya Nair",5,"Anti-ageing Ritual","The massage alone was worth it. I left feeling lighter and glowing."]];
const bk=[["Fri, 11:30 AM","Signature HydraFacial","Upcoming"],["12 Sep","Glow Peel","Completed"],["28 Aug","Skin analysis","Completed"],["10 Aug","Acne Therapy","Completed"]];
const hero=()=>`<section class="hero2 a">${IM("hero")}<div><h2>${gr}, ${fn}</h2><p>${adm?"24 visits are lined up today and 5 are waiting for your confirmation.":"Your glow score is 6 points higher than last month. Today's focus: hydrate and protect."}</p><button class="btn btn--p" data-go="${adm?"appointments":"routine"}">${adm?"Review appointments":"Start today's routine"}</button></div></section>`;
const tcard=(t,i)=>`<article class="box tc a" style="--i:${i}">${IM(t[1],t[0])}<div class="in"><h3>${t[0]}</h3><p class="d">${t[5]}</p><div class="meta"><span>${t[2]}</span><span>${t[3]}</span></div>${adm?`<small>Client satisfaction</small><div class="bar"><i style="width:${t[4]}%"></i></div><b class="pc">${t[4]}%</b>`:`<button class="btn" data-book="${t[0]}">Book this treatment</button>`}</div></article>`;
const rvRow=(r,i)=>`<div class="rv"><div class="av">${IM(av(i),r[0])}</div><div><b>${r[0]}</b> <span class="st" aria-label="${r[1]} out of 5">${stars(r[1])}</span><small>${r[2]}</small><p>${r[3]}</p></div></div>`;
const ov=V.overview;
V.overview=()=>hero()+ov()+(adm?`<div class="grid" style="margin-top:clamp(12px,2vw,20px)"><div class="box c7 a"><h3>Most booked this week</h3><div class="list">${TR.slice(0,4).map((t,i)=>`<div class="row"><div class="th">${IM(t[1],t[0])}</div><div class="t"><b>${t[0]}</b><span>${t[2]} · ${t[3]}</span></div><b style="color:var(--g)">${[38,27,22,15][i]} visits</b></div>`).join("")}</div></div><div class="box c5 a" style="--i:1"><h3>Latest reviews</h3>${RV.slice(0,3).map(rvRow).join("")}</div></div>`:`<div class="grid" style="margin-top:clamp(12px,2vw,20px)"><div class="box c7 a"><h3>Your skin journey</h3><div class="ba2" id="ba2"><img src="Assests/before.webp" alt="Skin before treatment" loading="lazy"><img class="af" src="Assests/after.webp" alt="Skin after treatment" loading="lazy"><i class="ln"></i><span class="tg1">Before</span><span class="tg2">After</span><input type="range" id="ba" min="5" max="95" value="50" aria-label="Compare before and after"></div><p style="color:var(--mu);margin-top:12px">Drag the slider to compare. A sample of results after a full course.</p></div><div class="box c5 a" style="--i:1;padding:0;overflow:hidden"><div class="tip">${IM("detail-hands","Gentle hands on face")}</div><div style="padding:20px"><h3>Glow tip of the day</h3><p style="color:#33433b">Press, don't rub. Pat your serum in with warm palms so it sinks in without stressing the skin barrier.</p><div class="tools" style="margin:14px 0 0"><span class="chip ok">2 min</span><span class="chip">Morning</span><span class="chip wait">Barrier care</span></div></div></div></div><h3 class="sec a">Recommended for you</h3><div class="tg">${TR.slice(0,3).map(tcard).join("")}</div>`);
V.treatments=()=>adm?`<div class="tg">${TR.map(tcard).join("")}</div>`:`<p class="lead a">Pick a treatment and we'll add it to your bookings. Our team will confirm a time with you.</p><div class="tg">${TR.map(tcard).join("")}</div>`;
V.clients=()=>`<div class="tools a"><input id="cs" placeholder="Search clients…" aria-label="Search clients"></div><div class="cards" id="cc">${clients.map((c,i)=>`<div class="box a" style="--i:${i}" data-k="${c[0].toLowerCase()}"><div class="av">${IM(av(i),c[0])}</div><b>${c[0]}</b><p style="color:var(--mu);font-size:.85rem">${c[1]}</p><span class="chip" style="margin-top:8px">${c[2]}</span></div>`).join("")}</div>`;
V.bookings=()=>`<div class="box a"><h3>My visits</h3><div class="tl">${bk.map(b=>`<div><b>${b[1]}</b><br><span style="color:var(--mu);font-size:.85rem">${b[0]}</span> <span class="chip ${b[2]==="Upcoming"?"wait":"ok"}">${b[2]}</span></div>`).join("")}</div><button class="btn" style="margin-top:20px" data-go="treatments">Book a treatment</button></div>`;
V.reviews=()=>`<div class="grid"><div class="box c4 a"><h3>Clinic rating</h3><div class="big">4.9</div><span class="st">★★★★★</span><p style="color:var(--mu);margin:6px 0 14px">From 312 reviews</p>${[["5",86],["4",11],["3",3]].map(r=>`<div class="rb"><span>${r[0]}★</span><div class="bar"><i style="width:${r[1]}%"></i></div><span>${r[1]}%</span></div>`).join("")}</div><div class="box c8 a" style="--i:1"><h3>What clients say</h3>${RV.map(rvRow).join("")}</div></div>`;
const JN=[["detail-cloth","Why your cleanser matters most","4 min read","A gentle cleanser sets the stage for everything else. Choose a low-foam formula, use lukewarm water and massage for 60 seconds so your serums can absorb properly."],["detail-mask","Mask nights: how often is too often?","3 min read","Hydrating masks suit two to three evenings a week. Clay masks are best once a week, and sensitive skin should always patch test first."],["detail-shadow","Sunscreen on cloudy days","3 min read","Most UV passes through clouds. Apply SPF 50 every morning, two finger-lengths for face and neck, and reapply after two hours outdoors."],["journal-1","What happens in a first consultation","5 min read","We start with a skin analysis, talk through your goals and routine, then build a plan with realistic timelines. No treatment is done on day one unless you want it."]];
V.journal=()=>`<div class="tg">${JN.map((j,i)=>`<details class="box tc a" style="--i:${i}">${IM(j[0],j[1])}<summary><h3>${j[1]}</h3><small>${j[2]}</small></summary><p class="d" style="padding:0 20px 20px">${j[3]}</p></details>`).join("")}</div>`;

const nav=adm?[["overview","◈","Overview"],["appointments","◷","Appointments"],["clients","☺","Clients"],["inbox","✉","Inbox"],["treatments","✦","Treatments"],["reviews","★","Reviews"]]:[["overview","◈","Overview"],["treatments","✦","Treatments"],["bookings","◷","My Bookings"],["routine","✿","My Routine"],["journal","✎","Journal"],["inbox","✉","Messages"],["profile","☺","Profile"]];
const T={overview:["Overview","Here's how things look today"],appointments:["Appointments","Manage today's visits"],clients:["Clients","People who trust your care"],inbox:["Inbox","Stay on top of every conversation"],treatments:adm?["Treatments","Performance at a glance"]:["Book a treatment","Choose your next ritual"],bookings:["My Bookings","Your visit history"],routine:["My Routine","Daily rituals for glowing skin"],profile:["Profile","Your personal details"],reviews:["Reviews","What clients say about you"],journal:["Journal","Skin tips from our care team"]};
/* ---- shell ---- */
const home=adm?"admin.html":"user.html";
$("#shell").innerHTML=`<aside class="side" id="side"><a class="logo" href="${home}" aria-label="Stackly - go to ${adm?'admin':'user'} dashboard"><img src="Assests/logo-light.webp" alt="Stackly" width="352" height="92"></a><span class="role">${adm?"Admin panel":"Member area"}</span><nav class="nav" id="nav">${nav.map(n=>`<button data-v="${n[0]}"><i>${n[1]}</i>${n[2]}${n[0]==="inbox"?'<span class="bd" id="bd"></span>':""}</button>`).join("")}</nav><a class="out" href="index.html">← Back to home</a><button class="out" id="lo">Logout</button></aside>
<main class="main"><div class="top"><button class="burger" id="bg" aria-label="Menu"><b></b><b></b><b></b></button><a class="toplogo" href="${home}" aria-label="Stackly - go to ${adm?'admin':'user'} dashboard"><img src="Assests/logo.webp" alt="Stackly" width="352" height="92"></a><h1 id="ttl"></h1><div class="me"><div class="av">${ini(S.name)}</div><span>${S.name}</span></div></div><div id="view"></div></main>`;
const side=$("#side"),sc=$("#scrim"),menu=o=>{side.classList.toggle("on",o);sc.classList.toggle("on",o);$("#bg").classList.toggle("on",o)};
$("#bg").onclick=()=>menu(!side.classList.contains("on"));sc.onclick=()=>menu(0);
$("#lo").onclick=()=>{localStorage.removeItem("glowSession");location.href="login.html"};
const badge=()=>{const n=mails.filter(m=>m.un&&m.box==="in").length,b=$("#bd");b.textContent=n||"";b.style.display=n?"":"none"};
const count=()=>$$("[data-n]").forEach(e=>{const E=+e.dataset.n,p=e.dataset.p||"",t0=performance.now(),k=t=>{const q=Math.min((t-t0)/1300,1);e.textContent=p+Math.round(E*(1-Math.pow(1-q,3))).toLocaleString("en-IN");q<1&&requestAnimationFrame(k)};requestAnimationFrame(k)});
function go(v){$$("#nav button").forEach(b=>b.classList.toggle("on",b.dataset.v===v));$("#ttl").innerHTML=`${T[v][0]}<small>${T[v][1]}</small>`;const el=$("#view");el.innerHTML=`<div class="view">${V[v]()}</div>`;history.replaceState(null,"","#"+v);menu(0);scrollTo({top:0});count();wire(v)}
$("#nav").onclick=e=>{const b=e.target.closest("button");b&&go(b.dataset.v)};
function wire(v){
if(v==="overview"){const r=$("#ba");r&&r.addEventListener("input",()=>r.parentNode.style.setProperty("--x",r.value+"%"))}
if(v==="appointments")$("#ft").onclick=e=>{const b=e.target.closest("button");if(!b)return;$$("#ft button").forEach(x=>x.classList.toggle("on",x===b));$$("#al .row").forEach(r=>r.style.display=b.dataset.f==="all"||r.dataset.s===b.dataset.f?"":"none")};
if(v==="clients")$("#cs").oninput=e=>$$("#cc .box").forEach(c=>c.style.display=c.dataset.k.includes(e.target.value.toLowerCase())?"":"none");
if(v==="routine")$$(".chk").forEach(c=>c.onclick=()=>{c.classList.toggle("on");toast(c.classList.contains("on")?"Nice — step completed ✦":"Step unchecked")});
if(v==="profile")$("#pf").onsubmit=e=>{e.preventDefault();S.name=$("#pn").value.trim()||S.name;localStorage.glowSession=JSON.stringify(S);toast("Profile saved")};
if(v==="inbox")mail()}
/* ---- email (dynamic) ---- */
let box="in",q="",cur=null;
function mail(){const L=$("#ml"),R=$("#mr"),M=$("#mail");
const draw=()=>{const list=mails.filter(m=>(box==="un"?m.un&&m.box==="in":m.box===box)&&(m.from+m.sub).toLowerCase().includes(q));badge();
L.innerHTML=list.length?list.map((m,i)=>`<button class="mi ${m.un?"un":""} ${cur===m.id?"on":""}" data-id="${m.id}" style="--i:${i}"><div class="av">${ini(m.from)}</div><div class="t"><b>${m.from}</b><span>${m.sub}</span></div><small style="color:var(--mu);font-size:.7rem;flex:none">${m.time}</small></button>`).join(""):`<p style="color:var(--mu);padding:20px">Nothing here yet ✦</p>`};
const open=id=>{const m=mails.find(x=>x.id===id);if(!m)return;cur=id;m.un=0;M.classList.add("open");
R.innerHTML=`<button class="btn btn--g back2" id="bk">← Back</button><div class="av" style="width:54px;height:54px">${ini(m.from)}</div><h3>${m.sub}</h3><span style="color:var(--mu);font-size:.85rem">${m.box==="out"?"To":"From"}: ${m.from} · ${m.time}</span><p>${m.body}</p><div class="mail__b"><button class="btn" id="rp">Reply</button><button class="btn btn--g" id="dl">Delete</button></div><div id="cz"></div>`;
$("#bk").onclick=()=>{M.classList.remove("open")};$("#dl").onclick=()=>{mails=mails.filter(x=>x.id!==id);cur=null;empty();draw();M.classList.remove("open");toast("Message deleted")};$("#rp").onclick=()=>form(m.from,"Re: "+m.sub);draw()};
const empty=()=>R.innerHTML=`<div style="display:grid;place-items:center;height:100%;min-height:260px;color:var(--mu);text-align:center"><div><div style="font-size:3rem">✉</div>Select a message to read it</div></div>`;
const form=(to="",sub="")=>{M.classList.add("open");R.innerHTML=`<button class="btn btn--g back2" id="bk">← Back</button><h3>New message</h3><form class="compose" id="cf"><div class="fld"><input id="ct" value="${to}" placeholder=" "><label for="ct">To</label></div><div class="fld"><input id="cu" value="${sub}" placeholder=" "><label for="cu">Subject</label></div><div class="fld"><textarea id="cb" placeholder=" "></textarea><label for="cb">Write your message</label></div><p class="msg" id="cm"></p><button class="btn" type="submit">Send ✦</button></form>`;
$("#bk").onclick=()=>M.classList.remove("open");$("#cf").onsubmit=e=>{e.preventDefault();const t=$("#ct").value.trim(),b=$("#cb").value.trim();if(!t||!b){$("#cm").textContent="Please add a recipient and a message.";return}
mails.unshift({id:Date.now(),from:t,sub:$("#cu").value.trim()||"(no subject)",body:b,time:"Just now",un:0,box:"out"});box="out";$$("#mt button").forEach(x=>x.classList.toggle("on",x.dataset.b==="out"));toast("Message sent");M.classList.remove("open");empty();draw()}};
$("#mt").onclick=e=>{const b=e.target.closest("button");if(!b)return;box=b.dataset.b;$$("#mt button").forEach(x=>x.classList.toggle("on",x===b));draw()};
$("#ms").oninput=e=>{q=e.target.value.toLowerCase();draw()};$("#cmp").onclick=()=>form();L.onclick=e=>{const b=e.target.closest(".mi");b&&open(+b.dataset.id)};empty();draw()}
$("#view").addEventListener("click",e=>{const g=e.target.closest("[data-go]");if(g)return go(g.dataset.go);const b=e.target.closest("[data-book]");if(b){bk.unshift(["Next available",b.dataset.book,"Upcoming"]);toast(b.dataset.book+" added to My Bookings ✦")}});
const start=(location.hash||"").slice(1);go(V[start]?start:"overview");badge();
})();